/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.jesper.seckill.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.shaded.org.mockito.Mockito.*;
import org.smartunit.shaded.org.mockito.ArgumentMatchers;
import com.jesper.seckill.exception.GlobalException;
import com.jesper.seckill.result.CodeMsg;
import org.junit.runner.RunWith;
import org.smartunit.runtime.ExecutorServiceAnswer;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.smartunit.runtime.TransactionTemplateAnswer;
import org.smartunit.runtime.ViolatedAssumptionAnswer;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class GlobalException_SSTest extends GlobalException_SSTest_scaffolding {
// allCoveredLines:[17, 18, 19, 22]

  @Test(timeout = 4000)
  public void test_getCodeMsg_0()  throws Throwable  {
      //caseID:6c42948242ce193c9867e21ef6d75441
      //CoveredLines: [17, 18, 19, 22]
      //Assert: assertEquals(0, method_result.getCode());
      
      //mock codeMsg0
      CodeMsg codeMsg0 = mock(CodeMsg.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      GlobalException globalException0 = new GlobalException(codeMsg0);
      
      //Call method: getCodeMsg
      CodeMsg codeMsg1 = globalException0.getCodeMsg();
      
      //Test Result Assert
      assertEquals(0, codeMsg1.getCode());
  }
}
